### ISSUE TITLE
Crossasia nicht erreichbar

### ISSUE THREAD

**Issue by wwwubhd** [UB-Heidelberg/UBHD_OMPXAsia#1]
@kadowa 
Crossasia ist nicht erreichbar. Diese Fehlermeldung wird ausgegeben: Admin is disabled because insecure channel

**Comment by kadowa** [comment]
Sorry, da hab ich wohl beim Rechte ändern was kaputt gemacht. Jetzt sollte es wieder gehen.

**Comment by wwwubhd** [comment]
@kadowa 
Ja, es geht wieder :-)

**Comment by kadowa** [comment]
Dann einfach das Issue schließen. :-)

Am 11.02.2016 um 10:56 schrieb WWW-Team UB Heidelberg:
